# Generated by Django 5.2.6 on 2025-10-01 05:19

import products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_product_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=products.models.product_image_path,
                verbose_name="Изображение товара",
            ),
        ),
    ]
